[package]
name = "tailsend-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
tailsend-core = { workspace = true }
tailsend-protocol = { workspace = true }
tailsend-transport-api = { workspace = true }
tailsend-platform-api = { workspace = true }
tailsend-transfer = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true }
log = { workspace = true }
getrandom = { workspace = true }
console_error_panic_hook = "0.1"
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = "0.6"
bytes = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]
