[package]
name = "tauri-plugin-ponlet-platform"
version = "0.1.0"
edition = "2021"
links = "tauri-plugin-ponlet-platform"
license = "MIT"

[build-dependencies]
tauri-plugin = { version = "2.6", features = ["build"] }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { version = "=2.11.5", default-features = false }
tailsend-telemetry = { workspace = true }

[target.'cfg(target_os = "ios")'.dependencies]
tauri = { version = "=2.11.5", default-features = false, features = ["wry"] }
