[package]
name = "tailsend-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tailsend-protocol = { workspace = true }
tailsend-transport-api = { workspace = true }
tailsend-platform-api = { workspace = true }
tailsend-transfer = { workspace = true }
tailsend-qr = { workspace = true }
tailsend-telemetry = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
getrandom = { workspace = true }
web-time = "1.1"

[dev-dependencies]
tokio = { workspace = true }
