import test from 'node:test';import assert from 'node:assert/strict';import {createGateway} from '../src/gateway.mjs';import {readConfig} from '../src/config.mjs';import {FIXTURE_ENV} from './fixtures/config.mjs';
function fixture(){const calls={rate:0,objects:0,auth:0};const runtime=()=>({config:readConfig(FIXTURE_ENV),auth:{verifyAppCheck:async token=>{calls.auth++;return {ok:token==='fixture-appcheck'};}}});const gateway=createGateway({runtime});const env={PRIVACY_RATE_LIMIT:{limit:async()=>{calls.rate++;return {success:true};}},DIAGNOSTIC_EPOCHS:{idFromName(kid){calls.objects++;return kid;},get(){return {fetch:async()=>new Response('{}',{status:200})};}}};return {calls,gateway,env};}
const request=(path,body,headers={})=>new Request('https://privacy.example.test'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','CF-Connecting-IP':'198.51.100.42','Ponlet-Privacy-Key':'A'.repeat(43),'X-Firebase-AppCheck':'fixture-appcheck',...headers},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body)});
test('gateway defaults to disabled capabilities if runtime setup is missing',async()=>{const g=createGateway({runtime(){throw new Error('private_env_error');}});const r=await g.fetch(request('/v1/capabilities'),{});assert.equal((await r.json()).remoteDeletionEnabled,false);assert.equal((await g.fetch(request('/v1/requests',{}),{})).status,503);});
test('namespace and rate-limit bindings are mandatory',async()=>{const h=fixture();assert.equal((await h.gateway.fetch(request('/v1/requests',{}),{})).status,503);assert.equal((await (await h.gateway.fetch(request('/v1/capabilities'),{})).json()).remoteDeletionEnabled,false);assert.equal(h.calls.objects,0);});
test('gateway rejects overlong bodies and query strings before allocating objects',async()=>{const h=fixture();assert.equal((await h.gateway.fetch(request('/v1/requests','x'.repeat(8193)),h.env)).status,413);assert.equal((await h.gateway.fetch(request('/v1/requests?private=id',{}),h.env)).status,400);assert.equal(h.calls.objects,0);});
test('registration/create challenges need attestation before DO allocation',async()=>{const h=fixture();for(const path of ['/v1/enrollments','/v1/requests']){const r=await h.gateway.fetch(request('/v1/challenges',{schemaVersion:1,kid:'A'.repeat(43),method:'POST',path},{'X-Firebase-AppCheck':'rejected'}),h.env);assert.equal(r.status,403);}assert.equal(h.calls.objects,0);});
test('status challenge stays available without renewed App Check but is rate-limited',async()=>{const h=fixture();const r=await h.gateway.fetch(request('/v1/challenges',{schemaVersion:1,kid:'A'.repeat(43),method:'GET',path:'/v1/requests/11111111-1111-4111-8111-111111111111'},{'X-Firebase-AppCheck':''}),h.env);assert.equal(r.status,200);assert.equal(h.calls.rate,1);assert.equal(h.calls.auth,0);assert.equal(h.calls.objects,1);});
test('rate-limit failure blocks actor allocation and exposes only enum error',async()=>{const h=fixture();h.env.PRIVACY_RATE_LIMIT.limit=async()=>({success:false});const r=await h.gateway.fetch(request('/v1/requests',{}),h.env);assert.equal(r.status,429);assert.deepEqual(await r.json(),{error:{code:'rate_limited'}});assert.equal(h.calls.objects,0);});
test('mistyped bindings never advertise remote deletion capability',async()=>{const h=fixture();const env={DIAGNOSTIC_EPOCHS:'not-a-binding',PRIVACY_RATE_LIMIT:{limit:'not-callable'}};const r=await h.gateway.fetch(request('/v1/capabilities'),env);assert.equal((await r.json()).remoteDeletionEnabled,false);});
test('actual entry reuses authentication runtime per environment instead of re-fetching JWKS state',async()=>{
 const {readFile}=await import('node:fs/promises');let source=await readFile(new URL('../src/entry.mjs',import.meta.url),'utf8');source=source.replace(/^import[^\n]+\n/gm,'').replace('export default createGateway({runtime});','const exportedGateway=createGateway({runtime});').replace('export class DiagnosticEpoch','class DiagnosticEpoch');
 let authCreations=0;const mocks={DurableObject:class{},readConfig:()=>readConfig(FIXTURE_ENV),createAuth:()=>{authCreations++;return {verifyAppCheck:async()=>({ok:true})};},createGoogleProviders:()=>({}),createServiceAccountTokenProvider:()=>({configured:true}),createDurableStore:()=>({}),createDeletionService:()=>({}),createRandomIds:()=>()=>'',ApiError:class extends Error{},errorResponse:()=>{},createGateway};
 const compiled=new Function(...Object.keys(mocks),source+'\nreturn exportedGateway;')(...Object.values(mocks));const h=fixture();await compiled.fetch(request('/v1/capabilities'),h.env);await compiled.fetch(request('/v1/capabilities'),h.env);assert.equal(authCreations,1);await compiled.fetch(request('/v1/capabilities'),{...h.env});assert.equal(authCreations,2);
});
test('slow or never-ending request body times out without allocating an actor',async()=>{
 const calls=[];const gateway=createGateway({runtime:()=>({config:readConfig({...FIXTURE_ENV,MAX_BODY_READ_MS:'20'}),auth:{verifyAppCheck:async()=>({ok:true})}})});
 const stream=new ReadableStream({start(controller){controller.enqueue(new TextEncoder().encode('{'));}});
 const req=new Request('https://privacy.example.test/v1/requests',{method:'POST',duplex:'half',headers:{'Content-Type':'application/json','CF-Connecting-IP':'198.51.100.42','Ponlet-Privacy-Key':'A'.repeat(43)},body:stream});
 const h=fixture();h.env.DIAGNOSTIC_EPOCHS.idFromName=()=>{calls.push('actor');};const response=await gateway.fetch(req,h.env);assert.equal(response.status,503);assert.deepEqual(calls,[]);void req.body.cancel();
});
test('Cloudflare alarm retains an accepted request schedule during configuration outage',async()=>{
 const {readFile}=await import('node:fs/promises');let source=await readFile(new URL('../src/entry.mjs',import.meta.url),'utf8');source=source.replace(/^import[^\n]+\n/gm,'').replace('export default createGateway({runtime});','const exportedGateway=createGateway({runtime});').replace('export class DiagnosticEpoch','class DiagnosticEpoch');
 const state={epoch:{ownerKey:'A'.repeat(43)},receipt:{requestId:'fixture'},challenges:{expired:{expiresAt:1}},recoveryDelayMs:3600000,alarmAt:1};
 const store={read:async()=>structuredClone(state),transaction:async update=>update(state)};
 const mocks={DurableObject:class{},readConfig:()=>{const e=new Error('not_configured');e.code='not_configured';throw e;},createAuth:()=>{},createGoogleProviders:()=>{},createServiceAccountTokenProvider:()=>{},createDurableStore:()=>store,createDeletionService:()=>{},createRandomIds:()=>()=>'',ApiError:class extends Error{},errorResponse:()=>{},createGateway};
 const Klass=new Function(...Object.keys(mocks),source+'\nreturn DiagnosticEpoch;')(...Object.values(mocks));const instance=new Klass({storage:{}},{});const start=Date.now();await instance.alarm();assert.ok(state.alarmAt>=start+3600000);assert.deepEqual(state.challenges,{});assert.equal(state.receipt.requestId,'fixture');
});
test('Cloudflare alarm preserves pending mapping cleanup after receipt expiry during configuration outage',async()=>{
 const {readFile}=await import('node:fs/promises');let source=await readFile(new URL('../src/entry.mjs',import.meta.url),'utf8');source=source.replace(/^import[^\n]+\n/gm,'').replace('export default createGateway({runtime});','const exportedGateway=createGateway({runtime});').replace('export class DiagnosticEpoch','class DiagnosticEpoch');
 const state={epoch:{ownerKey:'A'.repeat(43)},receipt:null,mappingPurgeAt:1,challenges:{expired:{expiresAt:1}},recoveryDelayMs:3600000,alarmAt:1};
 const store={read:async()=>structuredClone(state),transaction:async update=>update(state)};
 const mocks={DurableObject:class{},readConfig:()=>{const e=new Error('not_configured');e.code='not_configured';throw e;},createAuth:()=>{},createGoogleProviders:()=>{},createServiceAccountTokenProvider:()=>{},createDurableStore:()=>store,createDeletionService:()=>{},createRandomIds:()=>()=>'',ApiError:class extends Error{},errorResponse:()=>{},createGateway};
 const Klass=new Function(...Object.keys(mocks),source+'\nreturn DiagnosticEpoch;')(...Object.values(mocks));const instance=new Klass({storage:{}},{});const start=Date.now();await instance.alarm();assert.ok(state.alarmAt>=start+3600000);assert.deepEqual(state.challenges,{});assert.equal(state.receipt,null);assert.equal(state.mappingPurgeAt,1);
});
